#! /usr/bin/env python  

import rospy  
import rospkg

# Import the service message used by the service /execute_trajectory

from iri_wam_reproduce_trajectory.srv import ExecTraj, ExecTrajRequest  
import sys 
rospack = rospkg.RosPack()  

# Initialise a ROS node with the name service_client  

  

rospy.init_node('service_client')  

  

# Wait for the service client /execute trajectory to be running  

  

rospy.wait_for_service('/execute_trajectory')  

  

# Create the connection to the service  

  

execute_trajectory_service = rospy.ServiceProxy('/execute_trajectory', ExecTraj)  

  

# Create an object of type ExecTraj Request  

  

execute_trajectory_object = ExecTrajRequest() 

  

# Fill the variable model_name of this object with the desired value  

  

traj = rospack.get_path('iri_wam_reproduce_trajectory') + "/config/get_food.txt" 

execute_trajectory_object.file = traj 

  

  

result = execute_trajectory_service(execute_trajectory_object) 

print result 
